
import tempfile
from pathlib import Path

from fpdf import FPDF
from streamlit import pdf

from src.application.ports.document_export_port import DocumentExportPort
from src.domain.entities import story
from src.domain.entities.story import Story


class PDFExportAdapter(DocumentExportPort):
    def export_story(
        self,
        story: Story,
        cover_image_bytes: bytes | None = None,
        include_cover_image: bool = True,
    ) -> bytes:
        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)

        pdf.add_page()

        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, "EchoGate", ln=True, align="C")

        pdf.ln(10)

        pdf.set_font("Helvetica", "B", 26)
        pdf.multi_cell(0, 12, self._clean_pdf_text(story.title), align="C")

        pdf.ln(4)

        pdf.set_font("Helvetica", "", 13)
        pdf.cell(
            0,
            10,
            self._clean_pdf_text(f"A {story.tone} {story.genre} Adventure"),
            ln=True,
            align="C",
        )

        pdf.cell(
            0,
            10,
            self._clean_pdf_text(f"Protagonist: {story.protagonist_role}"),
            ln=True,
            align="C",
        )

        if include_cover_image and cover_image_bytes:
            image_bottom_y = self._add_cover_image(
                pdf=pdf,
                cover_image_bytes=cover_image_bytes,
                y_position=90,
            )
            pdf.set_y(image_bottom_y + 10)
        else:
            pdf.ln(20)

        pdf.set_font("Helvetica", "I", 11)
        pdf.cell(0, 10, "Generated by EchoGate AI", ln=True, align="C")

        for chapter in story.chapters:
            pdf.add_page()
            pdf.set_font("Helvetica", "B", 18)
            pdf.cell(
                0,
                10,
                self._clean_pdf_text(
                    f"Chapter {chapter.number}: {chapter.title}"),
                ln=True,
            )

            pdf.ln(5)
            pdf.set_font("Helvetica", "", 12)
            pdf.multi_cell(0, 8, self._clean_pdf_text(chapter.content))

        pdf.add_page()
        pdf.set_font("Helvetica", "B", 18)
        pdf.cell(0, 10, "Final Ending", ln=True)

        pdf.ln(5)
        pdf.set_font("Helvetica", "", 12)
        pdf.multi_cell(0, 8, self._clean_pdf_text(story.final_ending))

        pdf_bytes = pdf.output(dest="S")

        if isinstance(pdf_bytes, str):
            return pdf_bytes.encode("latin-1")

        return bytes(pdf_bytes)

    def _add_cover_image(
        self,
        pdf: FPDF,
        cover_image_bytes: bytes,
        y_position: float,
    ) -> float:
        with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as temp_file:
            temp_file.write(cover_image_bytes)
            temp_image_path = Path(temp_file.name)

        try:
            page_width = pdf.w
            image_width = 120
            x_position = (page_width - image_width) / 2

            pdf.image(
                str(temp_image_path),
                x=x_position,
                y=y_position,
                w=image_width,
            )

            return y_position + 90

        finally:
            temp_image_path.unlink(missing_ok=True)

    def _clean_pdf_text(self, text: str | None) -> str:
        if not text:
            return ""

        replacements = {
            "\u2018": "'",   # left single quote
            "\u2019": "'",   # right single quote
            "\u201c": '"',   # left double quote
            "\u201d": '"',   # right double quote
            "\u2013": "-",   # en dash
            "\u2014": "-",   # em dash
            "\u2026": "...",  # ellipsis
            "\u00a0": " ",   # non-breaking space
        }

        for old, new in replacements.items():
            text = text.replace(old, new)

        return text.encode("latin-1", errors="replace").decode("latin-1")
